In [1]:
#!/usr/bin/env python
import numpy as np

A simple 2×3 example

In [2]:
A = np.array([[3., 2.,  2.],
              [2., 3., -2.]])

Compute SVD: A = U Σ Vᵀ

In [3]:
U, σ, Vᵀ = np.linalg.svd(A, full_matrices=False)  # Vt is Vᵀ
Σ = np.diag(σ)

In [4]:
np.set_printoptions(precision=6, suppress=True)
print("A =\n", A)
print("\nU =\n", U)
print("\nΣ = diag(σ) =\n", Σ)
print("\nVᵀ =\n", Vᵀ)

A =
 [[ 3.  2.  2.]
 [ 2.  3. -2.]]

U =
 [[-0.707107 -0.707107]
 [-0.707107  0.707107]]

Σ = diag(σ) =
 [[5. 0.]
 [0. 3.]]

Vᵀ =
 [[-0.707107 -0.707107 -0.      ]
 [-0.235702  0.235702 -0.942809]]


Verify orthonormality and reconstruction

In [5]:
I_U = U.T @ U
I_V = Vᵀ@ Vᵀ.T
à = U @ Σ @ Vᵀ

In [6]:
print("\nUᵀU ≈ I =\n", I_U)
print("\nVᵀV ≈ I =\n", I_V)
print("\nReconstruction U Σ Vᵀ =\n", Ã)
print("\n‖A − U Σ Vᵀ‖_F =", np.linalg.norm(A - Ã, ord="fro"))


UᵀU ≈ I =
 [[1. 0.]
 [0. 1.]]

VᵀV ≈ I =
 [[1. 0.]
 [0. 1.]]

Reconstruction U Σ Vᵀ =
 [[ 3.  2.  2.]
 [ 2.  3. -2.]]

‖A − U Σ Vᵀ‖_F = 1.5543122344752192e-15
