In [1]:
#!/usr/bin/env python
import numpy as np
np.set_printoptions(precision=6, suppress=True)

A simple 2×3 example

In [2]:
A = np.array([[3., 2.,  2.],
              [2., 3., -2.]])

Compute SVD: A = U Σ Vᵀ

In [3]:
U, σ, Vᵀ = np.linalg.svd(A, full_matrices=False)  # Vt is Vᵀ
Σ = np.diag(σ)

Verify orthonormality and reconstruction

In [4]:
I_U = U.T @ U
I_V = Vᵀ@ Vᵀ.T
à = U @ Σ @ Vᵀ

In [5]:
print("\nUᵀU ≈ I =\n", I_U)
print("\nVᵀV ≈ I =\n", I_V)
print("\nReconstruction U Σ Vᵀ =\n", Ã)
print("\n‖A − U Σ Vᵀ‖_F =", np.linalg.norm(A - Ã, ord="fro"))


UᵀU ≈ I =
 [[1. 0.]
 [0. 1.]]

VᵀV ≈ I =
 [[1. 0.]
 [0. 1.]]

Reconstruction U Σ Vᵀ =
 [[ 3.  2.  2.]
 [ 2.  3. -2.]]

‖A − U Σ Vᵀ‖_F = 1.5543122344752192e-15
