In [1]:
#!/usr/bin/env python
import numpy as np

Define the matrix A

In [2]:
A = np.array([[ 3.07, -0.82, -2.23],
              [-0.82,  4.09, -0.31],
              [-2.23, -0.31,  1.84]], dtype=float)

Define column eigenvectors

In [3]:
v1 = np.array([[ 0.74],
               [-0.49],
               [-0.47]])

In [4]:
v2 = np.array([[-0.29],
               [-0.85],
               [ 0.43]])

In [5]:
v3 = np.array([[ 0.61],
               [ 0.18],
               [ 0.77]])

Eigenvalues

In [6]:
λ1, λ2, λ3 = 5.0, 4.0, 1e-4

Stack eigenvectors into V and build diagonal Λ

In [7]:
V = np.hstack([v1, v2, v3])
Λ = np.diag([λ1, λ2, λ3])

Check orthonormality

In [8]:
print("VᵀV ≈")
print(V.T @ V)

VᵀV ≈
[[ 1.0086e+00 -2.0000e-04  1.3000e-03]
 [-2.0000e-04  9.9150e-01  1.2000e-03]
 [ 1.3000e-03  1.2000e-03  9.9740e-01]]


In [9]:
print(A,'\n')

[[ 3.07 -0.82 -2.23]
 [-0.82  4.09 -0.31]
 [-2.23 -0.31  1.84]] 



Full reconstruction using the spectral theorem

In [10]:
A_full = λ1 * (v1 @ v1.T) + λ2 * (v2 @ v2.T) + λ3 * (v3 @ v3.T)
print(A_full,'\n')

[[ 3.07443721 -0.82698902 -2.23775303]
 [-0.82698902  4.09050324 -0.31048614]
 [-2.23775303 -0.31048614  1.84415929]] 



In [11]:
A_appr = λ1 * (v1 @ v1.T) + λ2 * (v2 @ v2.T)
print(A_appr,'\n')

[[ 3.0744 -0.827  -2.2378]
 [-0.827   4.0905 -0.3105]
 [-2.2378 -0.3105  1.8441]] 

